# Generated by Django 5.2.6 on 2026-06-25 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=191, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('admin', 'Administratrice'), ('auteure', 'Auteure'), ('editrice', 'Éditrice')], default='auteure', max_length=20, verbose_name='Rôle')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Utilisatrice',
                'verbose_name_plural': 'Utilisatrices',
                'db_table': 'utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='CampagneNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=191, verbose_name='Titre de la campagne')),
                ('contenu', models.TextField(verbose_name="Corps de l'email")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('planifiee', 'Planifiée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_envoi', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('nombre_destinataires', models.PositiveIntegerField(default=0, verbose_name='Nombre de destinataires')),
                ('taux_ouverture', models.FloatField(default=0.0, verbose_name="Taux d'ouverture (%)")),
            ],
            options={
                'verbose_name': 'Campagne Newsletter',
                'verbose_name_plural': 'Campagnes Newsletter',
                'db_table': 'campagnes_newsletter',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sujet', models.CharField(max_length=191, verbose_name='Sujet')),
                ('type', models.CharField(choices=[('partenariat', 'Partenariat'), ('presse', 'Presse'), ('recrutement', 'Recrutement'), ('temoignage', 'Témoignage / Chronique'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type de demande')),
                ('message', models.TextField(verbose_name='Message')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'db_table': 'contacts',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=191, unique=True, verbose_name='Adresse email')),
                ('prenom', models.CharField(blank=True, max_length=80, verbose_name='Prénom')),
                ('actif', models.BooleanField(default=True, verbose_name='Abonnement actif')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('date_desinscription', models.DateTimeField(blank=True, null=True, verbose_name='Date de désabonnement')),
                ('source', models.CharField(choices=[('accueil', "Page d'accueil"), ('popup', 'Popup'), ('article', 'Article'), ('footer', 'Footer'), ('autre', 'Autre')], default='accueil', max_length=20, verbose_name="Source d'inscription")),
            ],
            options={
                'verbose_name': 'Abonnée Newsletter',
                'verbose_name_plural': 'Abonnées Newsletter',
                'db_table': 'newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/', verbose_name='Logo')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Partenariat actif')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Début du partenariat')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Fin du partenariat')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'db_table': 'partenaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug URL')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Rubrique active')),
            ],
            options={
                'verbose_name': 'Rubrique',
                'verbose_name_plural': 'Rubriques',
                'db_table': 'rubriques',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True, verbose_name='Nom du tag')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug URL')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=191, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=191, unique=True, verbose_name='Slug URL')),
                ('extrait', models.TextField(blank=True, verbose_name='Extrait / Résumé')),
                ('contenu', models.TextField(verbose_name='Contenu complet')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Image de couverture')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('en_une', models.BooleanField(default=False, verbose_name='Afficher en une')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('temps_lecture', models.PositiveIntegerField(default=5, verbose_name='Temps de lecture (min)')),
                ('auteure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteure')),
                ('rubrique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='magazine.rubrique', verbose_name='Rubrique')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'articles',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Chronique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=191, verbose_name='Titre du récit')),
                ('slug', models.SlugField(max_length=191, unique=True, verbose_name='Slug URL')),
                ('contenu', models.TextField(verbose_name='Contenu du récit')),
                ('anonyme', models.BooleanField(default=False, verbose_name='Récit anonyme')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chroniques/', verbose_name="Image d'illustration")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('auteure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chroniques', to=settings.AUTH_USER_MODEL, verbose_name='Auteure')),
            ],
            options={
                'verbose_name': 'Chronique de Reine',
                'verbose_name_plural': 'Chroniques de Reines',
                'db_table': 'chroniques',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('auteur_email', models.EmailField(max_length=254, verbose_name='Email (non affiché)')),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='magazine.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'db_table': 'commentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=191, verbose_name='Nom du fichier')),
                ('url', models.FileField(upload_to='mediatheque/', verbose_name='Fichier')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('pdf', 'PDF')], default='image', max_length=10, verbose_name='Type')),
                ('taille', models.PositiveIntegerField(default=0, verbose_name='Taille (Ko)')),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'upload")),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medias', to='magazine.article', verbose_name='Article associé')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médiathèque',
                'db_table': 'medias',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('type', models.CharField(choices=[('nouveau_commentaire', 'Nouveau commentaire'), ('nouveau_contact', 'Nouveau message de contact'), ('nouvel_abonne', 'Nouvelle abonnée newsletter'), ('nouvel_article', 'Nouvel article publié')], max_length=30, verbose_name='Type')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('appareil', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('desktop', 'Ordinateur'), ('tablette', 'Tablette')], max_length=10, verbose_name='Appareil')),
                ('date_visite', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de visite')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='magazine.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'db_table': 'statistiques',
                'ordering': ['-date_visite'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.article', verbose_name='Article')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': "Tag d'article",
                'verbose_name_plural': "Tags d'articles",
                'db_table': 'articles_tags',
                'unique_together': {('article', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, through='magazine.ArticleTag', to='magazine.tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='magazine.article', verbose_name='Article')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL, verbose_name='Utilisatrice')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'db_table': 'favoris',
                'ordering': ['-date_ajout'],
                'unique_together': {('utilisateur', 'article')},
            },
        ),
    ]
