# Generated by Django 5.2.6 on 2026-08-19 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_seed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Date')),
                ('nombre_visites', models.PositiveIntegerField(default=0, verbose_name='Nombre de visites')),
            ],
            options={
                'verbose_name': 'Visite du site',
                'verbose_name_plural': 'Visites du site',
                'db_table': 'visites_site',
                'ordering': ['-date'],
            },
        ),
    ]
